// examples/solid/ssr/basic/app/server.tsx
/// <reference types="vinxi/server" />
import { MetaProvider, renderTags } from "@solidjs/meta";
import { renderAsset } from "@vinxi/solid";
import {
	HydrationScript,
	NoHydration,
	Suspense,
	renderToStream,
	renderToStringAsync,
	ssr,
	useAssets,
} from "solid-js/web";
import { eventHandler } from "vinxi/runtime/server";

import App from "./app";

export default eventHandler(async (event) => {
	const clientManifest = import.meta.env.MANIFEST["client"];
	const assets = await clientManifest.inputs[clientManifest.handler].assets();
	const events = {};
	const tags = [];
	function Meta() {
		useAssets(() => ssr(renderTags(tags)) as any);
		return null;
	}

	const manifestJson = await clientManifest.json();
	const stream = renderToStream(
		() => (
			<MetaProvider tags={tags}>
				<App
					assets={
						<>
							<NoHydration>
								<Meta />
							</NoHydration>
							<Suspense>{assets.map((m) => renderAsset(m))}</Suspense>
						</>
					}
					scripts={
						<>
							<NoHydration>
								<HydrationScript />
								<script
									innerHTML={`window.manifest = ${JSON.stringify(
										manifestJson,
									)}`}
								></script>
								<script
									type="module"
									src={
										clientManifest.inputs[clientManifest.handler].output.path
									}
								/>
							</NoHydration>
						</>
					}
				/>
			</MetaProvider>
		),
		{
			onCompleteAll(info) {
				events["end"]?.();
			},
		},
	);

	// @ts-ignore
	stream.on = (event, listener) => {
		events[event] = listener;
	};

	event.node.res.setHeader("Content-Type", "text/html");
	return stream;
});

// examples/react/ssr/basic/app/server.tsx
/// <reference types="vinxi/server" />
import { renderAsset } from "@vinxi/react";
import React, { Suspense } from "react";
import { renderToPipeableStream } from "react-dom/server";
import { eventHandler } from "vinxi/runtime/server";

import App from "./app";

export default eventHandler(async (event) => {
	const clientManifest = import.meta.env.MANIFEST["client"];
	const assets = await clientManifest.inputs[clientManifest.handler].assets();
	const events = {};
	const stream = await new Promise(async (resolve) => {
		const stream = renderToPipeableStream(
			<App assets={<Suspense>{assets.map((m) => renderAsset(m))}</Suspense>} />,
			{
				onShellReady() {
					resolve(stream);
				},
				bootstrapModules: [
					clientManifest.inputs[clientManifest.handler].output.path,
				],
				bootstrapScriptContent: `window.manifest = ${JSON.stringify(
					await clientManifest.json(),
				)}`,
			},
		);
	});

	// @ts-ignore
	stream.on = (event, listener) => {
		events[event] = listener;
	};

	event.node.res.setHeader("Content-Type", "text/html");
	return stream;
});
