// examples/react-spa-tanstack-router/app/pages/posts/[postId].tsx
import { useLoader } from "@tanstack/react-loaders";
import { ErrorComponent } from "@tanstack/router";

import { NotFoundError } from "../../NotFoundError";

export const loader = async ({
	context: { loaderClient },
	params: { postId },
}) => {
	const postLoader = loaderClient.loaders.post;
	await postLoader.load({
		variables: postId,
	});

	// Return a curried hook!
	return () =>
		useLoader({
			loader: postLoader,
			variables: postId,
		});
};

export default function Page({ useLoader }) {
	const {
		state: { data: post },
	} = useLoader()();
	console.log("post", post);

	return (
		<div className="space-y-2">
			<h4 className="text-xl font-bold underline">{post.title}</h4>
			<div className="text-sm">{post.body}</div>
		</div>
	);
}

export function ErrorBoundary({ error }) {
	if (error instanceof NotFoundError) {
		return <div>{error.message}</div>;
	}

	return <ErrorComponent error={error} />;
}

// examples/solid/ssr/solid-start/src/routes/posts/[postId].tsx
import { useParams } from "@solidjs/router";
import { Suspense, createResource } from "solid-js";

import { fetchPost } from "../../db";

export default function Page() {
	const params = useParams();
	const [postLoader] = createResource(
		() => params.postId,
		(postId) => fetchPost(postId),
	);

	return (
		<Suspense>
			<div class="space-y-2">
				<h4 class="text-xl font-bold underline">{postLoader()?.title}</h4>
				<div class="text-sm">{postLoader()?.body}</div>
			</div>
		</Suspense>
	);
}
