// examples/solid/app/client.tsx
/// <reference types="vinxi/client" />
import { MetaProvider } from "@solidjs/meta";
import { NoHydration, Suspense, hydrate } from "solid-js/web";
import "vinxi/runtime/client";

import { createAssets } from "./Assets";
import App from "./app";

const Assets = createAssets();

hydrate(
	() => (
		<MetaProvider>
			<App
				assets={
					<>
						<NoHydration></NoHydration>
						<Suspense>
							<Assets />
						</Suspense>
					</>
				}
				scripts={
					<>
						<NoHydration></NoHydration>
					</>
				}
			/>
		</MetaProvider>
	),
	document,
);

// examples/react/app/client.tsx
/// <reference types="vinxi/client" />
import React, { Suspense } from "react";
import { Root, hydrateRoot } from "react-dom/client";
import "vinxi/runtime/client";

import { createAssets } from "./Assets";
import App from "./app";

const Assets = createAssets();
window.$root =
	window.$root ||
	hydrateRoot(
		document,
		<App
			assets={
				<Suspense>
					<Assets />
				</Suspense>
			}
		></App>,
	);

if (import.meta.hot) {
	import.meta.hot.accept((mod) => {
		if (mod) {
			const Assets = createAssets();
			window.$root?.render(
				<mod.App
					assets={
						<Suspense>
							<Assets />
						</Suspense>
					}
				/>,
			);
		}
	});
}

export { App };

declare global {
	interface Window {
		$root?: Root;
	}
}
