// examples/react/rsc/spa/app/client.tsx
/// <reference types="vinxi/types/client" />
import { createModuleLoader } from "@vinxi/react-server-dom/runtime";
import React, { Suspense, startTransition } from "react";
import { Root, createRoot, hydrateRoot } from "react-dom/client";
import "vinxi/client";

import { sayHello } from "./actions";
import { fetchServerAction } from "./fetchServerAction";
import { ServerComponent } from "./server-component";

document.addEventListener("click", async (e) => {
	console.log(sayHello, "hello");

	const result = await fetchServerAction("/_server", sayHello["$$id"], []);
	console.log(result);
	// sayHello();
});

globalThis.__vite__ = createModuleLoader({
	loadModule: async (id) => {
		return import.meta.env.MANIFEST["client"].chunks[id].import();
	},
});

createRoot(document).render(<ServerComponent url={window.location.pathname} />);

// examples/solid/ssr/basic/app/client.tsx
/// <reference types="vinxi/client" />
import { MetaProvider } from "@solidjs/meta";
import { createAssets } from "@vinxi/solid";
import { NoHydration, Suspense, hydrate } from "solid-js/web";
import "vinxi/runtime/client";

import { sayHello } from "./actions";
import App from "./app";

console.log(await sayHello());

const Assets = createAssets(
	import.meta.env.MANIFEST["client"].handler,
	import.meta.env.MANIFEST["client"],
);

hydrate(
	() => (
		<MetaProvider>
			<App
				assets={
					<>
						<NoHydration></NoHydration>
						<Suspense>
							<Assets />
						</Suspense>
					</>
				}
				scripts={
					<>
						<NoHydration></NoHydration>
					</>
				}
			/>
		</MetaProvider>
	),
	document,
);
