// packages/vinxi-solid/lazy-route.jsx
/// <reference types="vinxi/types/client" />

/** @jsxImportSource solid-js */
/// <reference types="vinxi/types/client" />
import { createComponent, lazy, onCleanup } from "solid-js";
import {
	appendStyles,
	cleanupStyles,
	preloadStyles,
	updateStyles,
} from "vinxi/css";

import { renderAsset } from "./render-asset";

export default function lazyRoute(
	component,
	clientManifest,
	serverManifest,
	exported = "default",
) {
	return lazy(async () => {
		if (import.meta.env.DEV) {
			let manifest = import.meta.env.SSR ? serverManifest : clientManifest;

			const mod = await manifest.inputs[component.src].import();
			if (!mod[exported])
				console.error(`Module ${component.src} does not export ${exported}`);
			const Component = mod[exported];
			let assets = await clientManifest.inputs?.[component.src].assets();
			const styles = assets.filter((asset) => asset.tag === "style");

			if (typeof window !== "undefined" && import.meta.hot) {
				import.meta.hot.on("css-update", (data) => {
					updateStyles(styles, data);
				});
			}

			const Comp = (props) => {
				if (typeof window !== "undefined") {
					appendStyles(styles);
				}

				onCleanup(() => {
					if (typeof window !== "undefined") {
						// remove style tags added by vite when a CSS file is imported
						cleanupStyles(styles);
					}
				});
				return [
					...assets.map((asset) => renderAsset(asset)),
					createComponent(Component, props),
				];
			};
			return { default: Comp };
		} else {
			const mod = await component.import();
			const Component = mod[exported];
			let assets = await clientManifest.inputs?.[component.src].assets();
			const styles = assets.filter(
				(asset) => asset.tag === "style" || asset.attrs.rel === "stylesheet",
			);
			if (typeof window !== "undefined") {
				preloadStyles(styles);
			}
			const Comp = (props) => {
				return [
					...styles.map((asset) => renderAsset(asset)),
					createComponent(Component, props),
				];
			};
			return { default: Comp };
		}
	});
}

// packages/vinxi-react/lazy-route.js
import React, { useLayoutEffect } from "react";
import { Fragment, createElement, forwardRef, lazy } from "react";
import { cleanupStyles, preloadStyles, updateStyles } from "vinxi/css";

import invariant from "./invariant.js";
import { renderAsset } from "./render-asset.js";

/**
 *
 * @param {string} id
 * @param {any} clientManifest
 * @param {any} serverManifest
 * @returns {React.FC<any>}
 */
export default function lazyRoute(
	component,
	clientManifest,
	serverManifest,
	exported = "default",
) {
	return lazy(async () => {
		if (import.meta.env.DEV) {
			let manifest = import.meta.env.SSR ? serverManifest : clientManifest;

			const mod = await manifest.inputs[component.src].import();
			invariant(
				mod[exported],
				`Module ${component.src} does not export ${exported}`,
			);
			const Component = mod[exported];
			let assets = await clientManifest.inputs?.[component.src].assets();
			const styles = assets.filter((asset) => asset.tag === "style");

			if (typeof window !== "undefined" && import.meta.hot) {
				import.meta.hot.on("css-update", (data) => {
					updateStyles(styles, data);
				});
			}

			const Comp = forwardRef((props, ref) => {
				useLayoutEffect(() => {
					return () => {
						// remove style tags added by vite when a CSS file is imported
						cleanupStyles(styles);
					};
				}, []);
				return createElement(
					Fragment,
					null,
					...assets.map((asset) => renderAsset(asset)),
					createElement(Component, { ...props, ref: ref }),
				);
			});
			return { default: Comp };
		} else {
			const mod = await component.import();

			const Component = mod[exported];
			let assets = await clientManifest.inputs?.[component.src].assets();

			if (typeof window !== "undefined") {
				const styles = assets.filter(
					(asset) => asset.attrs.rel === "stylesheet",
				);
				preloadStyles(styles);
			}

			const Comp = forwardRef((props, ref) => {
				return createElement(
					Fragment,
					null,
					...assets.map((asset) => renderAsset(asset)),
					createElement(Component, { ...props, ref: ref }),
				);
			});
			return { default: Comp };
		}
	});
}
